data:

  batch_size: 6
  val_batch_size: 6
  num_workers: 10
  save_nepoch: 50
  val_nepoch: 100
  data_fn: "everyday.{}.txt"
  
  data_dir: "../vq_jigsaw/latent_data/bottle_volume_constrained_rot/train/"
  data_val_dir: "../vq_jigsaw/latent_data/bottle_volume_constrained_rot/val/"
  category: "Bottle"
  rot_range: -1
  overfit: -1
  rot_in_getitem: False

  ignore_small_scale: False

  data_keys:
    - 'part_ids'
  num_pc_points: 5000  # points for all parts
  min_num_part: 2
  max_num_part: 20
  shuffle_parts: False
  all_category:
    - 'BeerBottle'
    - 'Bowl'
    - 'Cup'
    - 'DrinkingUtensil'
    - 'Mug'
    - 'Plate'
    - 'Spoon'
    - 'Teacup'
    - 'ToyFigure'
    - 'WineBottle'
    - 'Bottle'
    - 'Cookie'
    - 'DrinkBottle'
    - 'Mirror'
    - 'PillBottle'
    - 'Ring'
    - 'Statue'
    - 'Teapot'
    - 'Vase'
    - 'WineGlass'
  colors:
    - [0, 204, 0]
    - [204, 0, 0]
    - [0, 204, 0]
    - [127, 127, 0]
    - [127, 0, 127]
    - [0, 127, 127]
    - [76, 153, 0]
    - [153, 0, 76]
    - [76, 0, 153]
    - [153, 76, 0]
    - [76, 0, 153]
    - [153, 0, 76]
    - [204, 51, 127]
    - [204, 51, 127]
    - [51, 204, 127]
    - [51, 127, 204]
    - [127, 51, 204]
    - [127, 204, 51]
    - [76, 76, 178]
    - [76, 178, 76]
    - [178, 76, 76]
